name: Aternos AFK Bot

on:
  workflow_dispatch: # Isse tu button daba kar manually run kar sakega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start Bot
      env:
        SERVER_IP: ${{ secrets.Kiingdom_SmP.aternos.me }}
        SERVER_PORT: ${{ secrets.36463 }}
        BOT_NAME: ${{ secrets.WATCHDOG }}
      run: node index.js
